"""bmb-algo: Blazing fast algorithms powered by BMB — 90x faster than Python."""

from typing import List

# Dynamic Programming
def knapsack(weights: List[int], values: List[int], capacity: int) -> int: ...
def edit_distance(a: str, b: str) -> int: ...
def lcs(a: str, b: str) -> int: ...
def max_subarray(arr: List[int]) -> int: ...
def coin_change(coins: List[int], amount: int) -> int: ...
def lis(arr: List[int]) -> int: ...

# Graph
def dijkstra(adj_matrix: List[List[int]], source: int) -> List[int]: ...
def floyd_warshall(matrix: List[List[int]]) -> List[List[int]]: ...
def bfs_count(adj_matrix: List[List[int]], source: int) -> int: ...
def topological_sort(adj_matrix: List[List[int]]) -> List[int]: ...
def matrix_multiply(a: List[List[int]], b: List[List[int]]) -> List[List[int]]: ...
def matrix_transpose(matrix: List[List[int]]) -> List[List[int]]: ...

# Sort
def quicksort(arr: List[int]) -> List[int]: ...
def merge_sort(arr: List[int]) -> List[int]: ...
def heap_sort(arr: List[int]) -> List[int]: ...
def counting_sort(arr: List[int], max_val: int = ...) -> List[int]: ...

# Search
def binary_search(arr: List[int], target: int) -> int: ...

# Number Theory
def gcd(a: int, b: int) -> int: ...
def lcm(a: int, b: int) -> int: ...
def fibonacci(n: int) -> int: ...
def prime_count(n: int) -> int: ...
def nqueens(n: int) -> int: ...
def modpow(base: int, exp: int, modulus: int) -> int: ...

# Utility
def djb2_hash(s: str) -> int: ...
def power_set_size(n: int) -> int: ...
def is_sorted(arr: List[int]) -> bool: ...
def array_reverse(arr: List[int]) -> List[int]: ...
def array_rotate(arr: List[int], k: int) -> List[int]: ...
def unique_count(sorted_arr: List[int]) -> int: ...
def prefix_sum(arr: List[int]) -> List[int]: ...
def array_sum(arr: List[int]) -> int: ...
def array_min(arr: List[int]) -> int: ...
def array_max(arr: List[int]) -> int: ...
def bit_popcount(x: int) -> int: ...
def bit_set(value: int, pos: int) -> int: ...
def bit_clear(value: int, pos: int) -> int: ...
def bit_test(value: int, pos: int) -> bool: ...
def bit_toggle(value: int, pos: int) -> int: ...
def array_fill(n: int, value: int) -> List[int]: ...
def array_contains(arr: List[int], target: int) -> bool: ...
def array_index_of(arr: List[int], target: int) -> int: ...

# Cycle 2125: New algorithms
def shell_sort(arr: List[int]) -> List[int]: ...
def insertion_sort(arr: List[int]) -> List[int]: ...
def subset_sum(arr: List[int], target: int) -> bool: ...
def matrix_det(matrix: List[List[int]]) -> int: ...
def is_prime(n: int) -> bool: ...
def selection_sort(arr: List[int]) -> List[int]: ...
def bubble_sort(arr: List[int]) -> List[int]: ...
def array_product(arr: List[int]) -> int: ...
def is_palindrome_num(n: int) -> bool: ...
def digit_sum(n: int) -> int: ...
def kth_smallest(arr: List[int], k: int) -> int: ...
def array_mode(sorted_arr: List[int]) -> int: ...
def sorted_intersect_count(a: List[int], b: List[int]) -> int: ...
def two_sum(arr: List[int], target: int) -> tuple | None: ...
