"""bmb-algo: compiled algorithms powered by BMB (compile-time contracts → native code)."""

from typing import List, Sequence

# IntSeq: any int64 sequence. list/array.array('q') accepted; NumPy int64 arrays are
# additionally passed zero-copy at runtime (no per-element marshalling).
IntSeq = Sequence[int]

# Dynamic Programming
def knapsack(weights: IntSeq, values: IntSeq, capacity: int) -> int: ...
def edit_distance(a: str, b: str) -> int: ...
def lcs(a: str, b: str) -> int: ...
def max_subarray(arr: IntSeq) -> int: ...
def coin_change(coins: IntSeq, amount: int) -> int: ...
def lis(arr: IntSeq) -> int: ...

# Graph
def dijkstra(adj_matrix: List[List[int]], source: int) -> List[int]: ...
def floyd_warshall(matrix: List[List[int]]) -> List[List[int]]: ...
def bfs_count(adj_matrix: List[List[int]], source: int) -> int: ...
def topological_sort(adj_matrix: List[List[int]]) -> List[int]: ...
def matrix_multiply(a: List[List[int]], b: List[List[int]]) -> List[List[int]]: ...
def matrix_transpose(matrix: List[List[int]]) -> List[List[int]]: ...

# Sort
def quicksort(arr: List[int]) -> List[int]: ...
def merge_sort(arr: List[int]) -> List[int]: ...
def heap_sort(arr: List[int]) -> List[int]: ...
def counting_sort(arr: List[int], max_val: int = ...) -> List[int]: ...

# Search
def binary_search(arr: IntSeq, target: int) -> int: ...

# Number Theory
def gcd(a: int, b: int) -> int: ...
def lcm(a: int, b: int) -> int: ...
def fibonacci(n: int) -> int: ...
def prime_count(n: int) -> int: ...
def nqueens(n: int) -> int: ...
def modpow(base: int, exp: int, modulus: int) -> int: ...

# Utility
def djb2_hash(s: str) -> int: ...
def power_set_size(n: int) -> int: ...
def is_sorted(arr: IntSeq) -> bool: ...
def array_reverse(arr: List[int]) -> List[int]: ...
def array_rotate(arr: List[int], k: int) -> List[int]: ...
def unique_count(sorted_arr: IntSeq) -> int: ...
def prefix_sum(arr: List[int]) -> List[int]: ...
def array_sum(arr: IntSeq) -> int: ...
def array_min(arr: IntSeq) -> int: ...
def array_max(arr: IntSeq) -> int: ...
def bit_popcount(x: int) -> int: ...
def bit_set(value: int, pos: int) -> int: ...
def bit_clear(value: int, pos: int) -> int: ...
def bit_test(value: int, pos: int) -> bool: ...
def bit_toggle(value: int, pos: int) -> int: ...
def array_fill(n: int, value: int) -> List[int]: ...
def array_contains(arr: IntSeq, target: int) -> bool: ...
def array_index_of(arr: IntSeq, target: int) -> int: ...

# Cycle 2125: New algorithms
def shell_sort(arr: List[int]) -> List[int]: ...
def insertion_sort(arr: List[int]) -> List[int]: ...
def subset_sum(arr: IntSeq, target: int) -> bool: ...
def matrix_det(matrix: List[List[int]]) -> int: ...
def is_prime(n: int) -> bool: ...
def selection_sort(arr: List[int]) -> List[int]: ...
def bubble_sort(arr: List[int]) -> List[int]: ...
def array_product(arr: IntSeq) -> int: ...
def is_palindrome_num(n: int) -> bool: ...
def digit_sum(n: int) -> int: ...
def kth_smallest(arr: List[int], k: int) -> int: ...
def array_mode(sorted_arr: List[int]) -> int: ...
def sorted_intersect_count(a: List[int], b: List[int]) -> int: ...
def two_sum(arr: List[int], target: int) -> tuple | None: ...
