"""bmb-crypto: Fast cryptographic functions powered by BMB."""

def sha256(data: str) -> str: ...
def md5(data: str) -> str: ...
def crc32(data: str) -> str: ...
def base64_encode(data: str) -> str: ...
def base64_decode(data: str) -> str: ...
def base32_encode(data: str) -> str: ...
def base32_decode(data: str) -> str: ...
def adler32(data: str) -> str: ...
def fletcher16(data: str) -> str: ...
def xor_checksum(data: str) -> str: ...
def hmac_sha256(key: str, msg: str) -> str: ...
