"""bmb-json: High-performance JSON parser powered by BMB."""

def validate(json_str: str) -> bool: ...
def stringify(json_str: str) -> str: ...
def get_type(json_str: str) -> str: ...
def get(json_str: str, key: str) -> str: ...
def get_string(json_str: str, key: str) -> str: ...
def get_number(json_str: str, key: str) -> int: ...
def array_len(json_str: str) -> int: ...
def array_get(json_str: str, idx: int) -> str: ...
