"""bmb-text: Fast string processing powered by BMB."""

# Search
def kmp_search(text: str, pattern: str) -> int: ...
def str_find(haystack: str, needle: str) -> int: ...
def str_rfind(haystack: str, needle: str) -> int: ...
def str_count(haystack: str, needle: str) -> int: ...
def str_contains(haystack: str, needle: str) -> bool: ...
def str_starts_with(s: str, prefix: str) -> bool: ...
def str_ends_with(s: str, suffix: str) -> bool: ...
def find_byte(s: str, byte: int) -> int: ...
def count_byte(s: str, byte: int) -> int: ...

# Analysis
def is_palindrome(s: str) -> bool: ...
def token_count(s: str, delimiter: str) -> int: ...
def hamming_distance(a: str, b: str) -> int: ...
def word_count(s: str) -> int: ...

# Transform
def str_reverse(s: str) -> str: ...
def str_replace(s: str, old: str, new: str) -> str: ...
def str_replace_all(s: str, old: str, new: str) -> str: ...
def to_upper(s: str) -> str: ...
def to_lower(s: str) -> str: ...
def trim(s: str) -> str: ...
def repeat(s: str, n: int) -> str: ...
