"""bmb-compute: High-performance numeric computation powered by BMB."""

from typing import List

# Math
def abs(x: int) -> int: ...
def min(a: int, b: int) -> int: ...
def max(a: int, b: int) -> int: ...
def clamp(x: int, lo: int, hi: int) -> int: ...
def sign(x: int) -> int: ...
def ipow(base: int, exp: int) -> int: ...
def sqrt(n: int) -> int: ...
def factorial(n: int) -> int: ...

# Statistics
def sum(arr: List[int]) -> int: ...
def mean_scaled(arr: List[int]) -> int: ...
def min_val(arr: List[int]) -> int: ...
def max_val(arr: List[int]) -> int: ...
def range_val(arr: List[int]) -> int: ...
def variance_scaled(arr: List[int]) -> int: ...

# Random
def rand_seed(seed: int) -> int: ...
def rand_next(state: int) -> int: ...
def rand_pos(state: int) -> int: ...
def rand_range(state: int, max_val: int) -> int: ...

# Vector
def dot_product(a: List[int], b: List[int]) -> int: ...
def dist_squared(a: List[int], b: List[int]) -> int: ...
def weighted_sum(values: List[int], weights: List[int]) -> int: ...
def lerp_scaled(a: int, b: int, t: int) -> int: ...

# Statistics (new)
def median_scaled(arr: List[int]) -> int: ...
def cumsum(arr: List[int]) -> List[int]: ...
def moving_avg_scaled(arr: List[int], k: int) -> List[int]: ...

# Vector (new)
def magnitude_squared(arr: List[int]) -> int: ...
def vec_add(a: List[int], b: List[int]) -> List[int]: ...
def vec_sub(a: List[int], b: List[int]) -> List[int]: ...
def vec_scale(arr: List[int], scalar: int) -> List[int]: ...
def map_square(arr: List[int]) -> List[int]: ...

# Utility
def is_power_of_two(n: int) -> bool: ...
def next_power_of_two(n: int) -> int: ...
